# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jerrit/Projects/Git/SpreadSimulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jerrit/Projects/Git/SpreadSimulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jerrit/Projects/Git/SpreadSimulator/CMakeFiles /home/jerrit/Projects/Git/SpreadSimulator/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jerrit/Projects/Git/SpreadSimulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SpreadSimulator

# Build rule for target.
SpreadSimulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SpreadSimulator
.PHONY : SpreadSimulator

# fast build rule for target.
SpreadSimulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/build
.PHONY : SpreadSimulator/fast

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/main.c.s
.PHONY : main.c.s

src/Entity.o: src/Entity.c.o

.PHONY : src/Entity.o

# target to build an object file
src/Entity.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/src/Entity.c.o
.PHONY : src/Entity.c.o

src/Entity.i: src/Entity.c.i

.PHONY : src/Entity.i

# target to preprocess a source file
src/Entity.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/src/Entity.c.i
.PHONY : src/Entity.c.i

src/Entity.s: src/Entity.c.s

.PHONY : src/Entity.s

# target to generate assembly for a file
src/Entity.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/src/Entity.c.s
.PHONY : src/Entity.c.s

src/Infectable.o: src/Infectable.c.o

.PHONY : src/Infectable.o

# target to build an object file
src/Infectable.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/src/Infectable.c.o
.PHONY : src/Infectable.c.o

src/Infectable.i: src/Infectable.c.i

.PHONY : src/Infectable.i

# target to preprocess a source file
src/Infectable.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/src/Infectable.c.i
.PHONY : src/Infectable.c.i

src/Infectable.s: src/Infectable.c.s

.PHONY : src/Infectable.s

# target to generate assembly for a file
src/Infectable.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/src/Infectable.c.s
.PHONY : src/Infectable.c.s

src/SpreadSimulationSettings.o: src/SpreadSimulationSettings.c.o

.PHONY : src/SpreadSimulationSettings.o

# target to build an object file
src/SpreadSimulationSettings.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/src/SpreadSimulationSettings.c.o
.PHONY : src/SpreadSimulationSettings.c.o

src/SpreadSimulationSettings.i: src/SpreadSimulationSettings.c.i

.PHONY : src/SpreadSimulationSettings.i

# target to preprocess a source file
src/SpreadSimulationSettings.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/src/SpreadSimulationSettings.c.i
.PHONY : src/SpreadSimulationSettings.c.i

src/SpreadSimulationSettings.s: src/SpreadSimulationSettings.c.s

.PHONY : src/SpreadSimulationSettings.s

# target to generate assembly for a file
src/SpreadSimulationSettings.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/src/SpreadSimulationSettings.c.s
.PHONY : src/SpreadSimulationSettings.c.s

src/SpreadSimulator.o: src/SpreadSimulator.c.o

.PHONY : src/SpreadSimulator.o

# target to build an object file
src/SpreadSimulator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/src/SpreadSimulator.c.o
.PHONY : src/SpreadSimulator.c.o

src/SpreadSimulator.i: src/SpreadSimulator.c.i

.PHONY : src/SpreadSimulator.i

# target to preprocess a source file
src/SpreadSimulator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/src/SpreadSimulator.c.i
.PHONY : src/SpreadSimulator.c.i

src/SpreadSimulator.s: src/SpreadSimulator.c.s

.PHONY : src/SpreadSimulator.s

# target to generate assembly for a file
src/SpreadSimulator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/src/SpreadSimulator.c.s
.PHONY : src/SpreadSimulator.c.s

src/Vector.o: src/Vector.c.o

.PHONY : src/Vector.o

# target to build an object file
src/Vector.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/src/Vector.c.o
.PHONY : src/Vector.c.o

src/Vector.i: src/Vector.c.i

.PHONY : src/Vector.i

# target to preprocess a source file
src/Vector.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/src/Vector.c.i
.PHONY : src/Vector.c.i

src/Vector.s: src/Vector.c.s

.PHONY : src/Vector.s

# target to generate assembly for a file
src/Vector.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpreadSimulator.dir/build.make CMakeFiles/SpreadSimulator.dir/src/Vector.c.s
.PHONY : src/Vector.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SpreadSimulator"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Entity.o"
	@echo "... src/Entity.i"
	@echo "... src/Entity.s"
	@echo "... src/Infectable.o"
	@echo "... src/Infectable.i"
	@echo "... src/Infectable.s"
	@echo "... src/SpreadSimulationSettings.o"
	@echo "... src/SpreadSimulationSettings.i"
	@echo "... src/SpreadSimulationSettings.s"
	@echo "... src/SpreadSimulator.o"
	@echo "... src/SpreadSimulator.i"
	@echo "... src/SpreadSimulator.s"
	@echo "... src/Vector.o"
	@echo "... src/Vector.i"
	@echo "... src/Vector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

